[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-streamlit.*]
ignore_missing_imports = True

[mypy-sqlcipher3.*]
ignore_missing_imports = True

[mypy-defusedxml.*]
ignore_missing_imports = True

[mypy-lxml.*]
ignore_missing_imports = True